# Generated by Django 4.2.2 on 2024-09-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_answer_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_first_name', models.CharField(max_length=100)),
                ('author_last_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('publication_date', models.IntegerField()),
                ('publisher', models.CharField(max_length=255)),
                ('translator', models.CharField(blank=True, max_length=100, null=True)),
                ('edition', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='answers', to='core.source'),
        ),
    ]
