# Generated by Django 4.2.2 on 2024-09-09 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_source_answer_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='sources',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
