# Generated by Django 4.2.2 on 2024-09-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
