# Generated by Django 4.2.2 on 2024-09-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_question_user_count_alter_answer_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='parent_question',
        ),
        migrations.AddField(
            model_name='question',
            name='parent_questions',
            field=models.ManyToManyField(blank=True, related_name='subquestions', to='core.question'),
        ),
    ]
