# Generated by Django 4.2.2 on 2024-10-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_question_parent_questions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='color',
            new_name='text_color',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='background_color',
            field=models.CharField(default='#F5F5F5', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='header_background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='header_text_color',
            field=models.CharField(default='#333333', max_length=7),
        ),
    ]
