# Generated by Django 4.2.2 on 2024-10-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_color_userprofile_text_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='button_background_color',
            field=models.CharField(default='#007bff', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='button_text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='link_color',
            field=models.CharField(default='#0d6efd', max_length=7),
        ),
    ]
