# Generated by Django 4.2.2 on 2024-10-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_userprofile_button_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='answer_background_color',
            field=models.CharField(default='#F5F5F5', max_length=7),
        ),
    ]
