# Generated by Django 4.2.2 on 2024-10-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_userprofile_content_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='button_hover_background_color',
            field=models.CharField(default='#0056b3', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dropdown_hover_background_color',
            field=models.CharField(default='#f2f2f2', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dropdown_hover_text_color',
            field=models.CharField(default='#0056b3', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dropdown_text_color',
            field=models.CharField(default='#333333', max_length=7),
        ),
    ]
